# Generated by Django 3.1 on 2021-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_pickup_station',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_postal_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_zip_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='send_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='send_to',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('In Transit', 'In Transit'), ('Waiting Disburse', 'Waiting Disburse')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_method',
            field=models.CharField(choices=[('Air Transport', 'Air Transport'), ('Sea Transport', 'Sea Transport'), ('Road Transport', 'Road Transport')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
