# Generated by Django 3.1 on 2021-06-25 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20210625_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='estimated_arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
